### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by edavalosanaya** [InteractiveGL/vision6D#18]
```

(plot3d) $ vision6D
Traceback (most recent call last):
  File "/home/nicole/anaconda3/envs/plot3d/bin/vision6D", line 5, in <module>
    from vision6D.entry.main import main
  File "/home/nicole/anaconda3/envs/plot3d/lib/python3.10/site-packages/vision6D/__init__.py", line 32, in <module>
    from .mainwindow import MyMainWindow
  File "/home/nicole/anaconda3/envs/plot3d/lib/python3.10/site-packages/vision6D/mainwindow/__init__.py", line 1, in <module>
    from .mainwindow import MyMainWindow
  File "/home/nicole/anaconda3/envs/plot3d/lib/python3.10/site-packages/vision6D/mainwindow/mainwindow.py", line 27, in <module>
    from ..widgets import CustomQtInteractor
  File "/home/nicole/anaconda3/envs/plot3d/lib/python3.10/site-packages/vision6D/widgets/__init__.py", line 7, in <module>
    from .draw_sam_window import SamWindow
  File "/home/nicole/anaconda3/envs/plot3d/lib/python3.10/site-packages/vision6D/widgets/draw_sam_window.py", line 18, in <module>
    from segment_anything import SamPredictor, sam_model_registry
ModuleNotFoundError: No module named 'segment_anything'

```

**Comment by edavalosanaya** [comment]
Also need to add ``torch``

**Comment by edavalosanaya** [comment]
Also need to add ``torchvision``
